### ISSUE TITLE
Core 4.22.1版本，无法正确加载geoip.dat和geosite.dat

### ISSUE THREAD

**Issue by xingzichen** [yuanmomo/AndroidLibV2rayLite#2]
已经成功用您的脚本编译出aar，但是在加载配置时，路由部分配置报如下错误
`
2020-03-20 01:02:13.240 15733-15793/com.***LibV2Ray I/GoLog: EscortRun Waiting....
2020-03-20 01:02:13.423 15733-15733/com.***LibV2Ray I/GoLog: v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > proto: can't skip unknown wire type 6
2020-03-20 01:02:13.424 15733-15733/com.***LibV2Ray D/com.***LibV2Ray: go.Universe$proxyerror: v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > proto: can't skip unknown wire type 6
2020-03-20 01:02:18.069 15733-15733/com.***LibV2Ray D/AwareBitmapCacher: handleInit disable 
`
配置文件如下：
`
{
	"dns": {
		"hosts": {
			"domain:googleapis.cn": "googleapis.com"
		},
		"servers": ["8.8.8.8", {
			"address": "114.114.114.114",
			"domains": ["geosite:cn"],
			"port": 53
		}]
	},
	"outbounds": [{
			"此处省略": "此处省略",
			"tag": "proxy"
		},
		{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		}, {
			"protocol": "blackhole",
			"settings": {
				"response": {
					"type": "http"
				}
			},
			"tag": "block"
		}, {
			"protocol": "dns",
			"tag": "dns-out"
		}
	],
	"inbounds": [{
		"port": 10808,
		"protocol": "socks",
		"settings": {
			"auth": "noauth",
			"udp": true,
			"userLevel": 8
		},
		"sniffing": {
			"destOverride": ["http", "tls"],
			"enabled": true
		},
		"tag": "socks"
	}, {
		"port": 10809,
		"protocol": "http",
		"settings": {
			"userLevel": 8
		},
		"tag": "http"
	}, {
		"port": 10807,
		"protocol": "dokodemo-door",
		"settings": {
			"address": "8.8.8.8",
			"network": "tcp,udp",
			"port": 53
		},
		"tag": "dns-in"
	}],
	"log": {
		"loglevel": "warning"
	},
	"policy": {
		"levels": {
			"8": {
				"connIdle": 300,
				"downlinkOnly": 1,
				"handshake": 4,
				"uplinkOnly": 1
			}
		},
		"system": {
			"statsInboundUplink": true,
			"statsInboundDownlink": true
		}
	},
	"stats": {}
}
`
经验证，若将所有geosite 和 geoip部分去掉，则可以正常运行。我初步判断为lib加载dat文件失败

望不吝赐教～

**Comment by yuanmomo** [comment]
这个geo的域名和ip文件不在这个库。需要你自己包含到项目。至于怎么获取到这个文件，应该要让Android 端看看怎么放的

邢梓宸 <notifications@github.com>于2020年3月22日 周日23:33写道：

**Comment by xingzichen** [comment]
打包出来的AAR中包含这两个，我看了您的脚本，有去获取这两个库的部分。
<img width="225" alt="Screenshot 2020-03-23 at 12 08 16 AM" src="https://user-images.githubusercontent.com/2193597/77254183-77451180-6c9a-11ea-8433-f1476f48ac3f.png">
这两个dat的加载应该是在so中吧？
我对go真的是看不懂哈～

**Comment by xingzichen** [comment]
强烈怀疑interact.go中的这一句哈
```
const (
	v2Assert    = "v2ray.location.asset"
	assetperfix = "/dev/libv2rayfs0/asset"
)
```
求证gomobile中获取assets是这个这个写法么

**Comment by yuanmomo** [comment]
不好意思，这个我真的不是很清楚，我之前是打出来的客户端，然后交给做Android开发的朋友他来集成的。

邢梓宸 <notifications@github.com>于2020年3月23日 周一00:16写道：

**Comment by xingzichen** [comment]
好嘞～ 在此谢过哈～ 如果有可能希望能帮忙问您朋友一句他的geosite.dat没问题么 😂
